# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None
project_root = Path.cwd()

a = Analysis(
    ['run_entropy.py'],
    pathex=[str(project_root), str(project_root / 'src')],
    binaries=[],
    datas=[
        ('entropy.ico', '.'),
        ('skills', 'skills'),
        ('AGENTS.md', '.'),
    ],
    hiddenimports=[
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngineCore',
        'pydantic',
        'sqlite3',
        'entropy',
        'entropy.core',
        'entropy.core.config',
        'entropy.core.event_bus',
        'entropy.core.agy_bridge',
        'entropy.core.task_ledger',
        'entropy.core.project_lock',
        'entropy.core.slash_commands',
        'entropy.core.provider',
        'entropy.core.claude_bridge',
        'entropy.core.masking',
        'entropy.core.perf_history',
        'entropy.ui',
        'entropy.ui.manager',
        'entropy.ui.themes.cyber_theme',
        'entropy.ui.widgets.core_visualizer',
        'entropy.ui.widgets.terminal_pane',
        'entropy.ui.widgets.reports_viewer',
        'entropy.ui.widgets.knowledge_graph',
        'entropy.ui.widgets.memory_inspector_dialog',
        'entropy.ui.widgets.standalone_report_window',
        'entropy.ui.widgets.mcp_drawer',
        'entropy.ui.widgets.slash_command_popup',
        'entropy.ui.modes.zen_mode',
        'entropy.ui.modes.floating_mode',
        'entropy.ui.modes.chat_mode',
        'entropy.ui.widgets.skills_widget',
        'entropy.ui.widgets.tasks_widget',
        'entropy.ui.widgets.notification_pill',
        'entropy.ui.widgets.token_badge',
        'entropy.ui.widgets.markdown_renderer',
        'entropy.ui.widgets.agents_widget',
        'entropy.ui.widgets.task_board_widget',
        'entropy.ui.widgets.ui_polish',
        'entropy.ui.widgets.report_inbox',
        'entropy.agents',
        'entropy.agents.registry',
        'entropy.agents.compile',
        'entropy.agents.tasks',
        'entropy.agents.offices',
        'entropy.agents.harness',
        'entropy.agents.bootstrap',
        'entropy.desk.window',
        'entropy.desk.scene',
        'entropy.desk.offices_panel',
        'entropy.desk.roster_panel',
        'entropy.desk.board_panel',
        'entropy.desk.stream_panel',
        'entropy.agents.watchers',
        'entropy.skills',
        'entropy.skills.manager',
        'entropy.skills.pdf_engine',
        'pypdf',
        'yaml',
        'entropy.memory',
        'entropy.memory.playbook',
        'entropy.memory.distiller',
        'entropy.memory.context_builder',
        'entropy.memory.report_watcher',
        'entropy.memory.handoff',
        'entropy.memory.obsidian.vault_manager',
        'entropy.memory.wiki',
        'entropy.memory.lint',
        'entropy.memory.agent_memory',
        'entropy.memory.office_memory',
        'entropy.memory.supabase.cognitive_memory',
        'numpy',
        'entropy.memory.rag.project_indexer',
        'entropy.tools',
        'entropy.tools.synthesizer',
        'entropy.mcp',
        'entropy.mcp.manager',
        'entropy.scheduler',
        'entropy.scheduler.cron_engine',
        'entropy.platform',
        'entropy.platform.autostart',
        'entropy.platform.clipboard',
        'entropy.desk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'scipy', 'pandas', 'IPython'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='EntropyAI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='entropy.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='EntropyAI',
)
